info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T10:55:42.483Z"}
info: Connected to the database. {"timestamp":"2023-02-16T10:55:51.531Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:10:58.302Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:11:09.015Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:15.382Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:28.769Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:37.466Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:17:41.598Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:21:41.123Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:21:46.515Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:24:24.558Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:24:28.953Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:24:42.367Z"}
error: 
    status - 500 
    message - ValidationError: "confirmPassword" length must be at least 8 characters long 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:25:09.003Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:30:59.100Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:31:08.503Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:54:59.467Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:55:04.070Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.symbol(...).string is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:25)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:55:07.568Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.symbol(...).string is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:25)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:55:18.913Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:15:22.487Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:16:38.488Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:16:46.382Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.allow(...).min is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:45)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:17:00.498Z"}
error: Could not connect to the database. Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/ {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12\n    at database (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-16T13:18:02.943Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:22:53.645Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:23:04.646Z"}
error: 
    status - 500 
    message - ReferenceError: Regex is not defined
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:38)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:26:18.082Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:28:07.034Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:28:26.537Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:29:58.842Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:57:46.425Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:57:56.609Z"}
error: 
    status - 500 
    message - ValidationError: "confirmPassword" is required 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:58:18.804Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:58:39.689Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:58:48.543Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:58:52.532Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T14:08:21.622Z"}
info: Connected to the database. {"timestamp":"2023-02-16T14:08:25.874Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:24.316Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:29.683Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:34.603Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:38.713Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:47.625Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:51.153Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:46:12.049Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:46:17.437Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:47:15.468Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:47:19.616Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:53:34.160Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:53:43.259Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:33.399Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:45.872Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:53.342Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:59:03.586Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:59:13.081Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:00:23.267Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:00:58.617Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:02:07.687Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:02:11.735Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:02:32.782Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:08:12.162Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:08:15.940Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:15:10.135Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:15:19.573Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:16:08.321Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:16:12.012Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:16:16.736Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:17:49.519Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:18:14.419Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:18:19.047Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:18:22.769Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:18:31.624Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:19:06.966Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:19:10.814Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:37:26.696Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:37:31.473Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T17:05:28.667Z"}
info: Connected to the database. {"timestamp":"2023-02-16T17:05:34.006Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/newuser/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T17:17:45.158Z"}
